Add suggestion on fixing Pupil Mobile network lag
pupil-labs/pupil pull request #1994
Opened 2020-08-24 07:34 UTC by romanroibu

2020-08-24 07:53 UTC, papr commented on pupil_src/shared_modules/recorder.py
> +                    "Try turning down camera resolution and/or frame rate."
```suggestion
                    "Recording a Pupil Mobile stream requires a stable "
                    "connection. Aborting recording. Try turning down "
                    "camera resolution and/or frame rate."
```

2020-08-24 08:13 UTC, papr requested changes

2020-08-24 08:13 UTC, papr commented on pupil_src/shared_modules/recorder.py
> +                    "Try turning down camera resolution and/or frame rate."
After discussing this message in a meeting, we have decided on this wording:
```suggestion
                    "Your connection does not seem to be stable enough for "
                    "recording Pupil Mobile via WiFi. We recommend recording "
                    "on the phone."
```

2020-08-24 08:13 UTC, pfaion approved these changes

2020-08-25 07:59 UTC, papr approved these changes

2020-08-25 07:59 UTC, merged