Added imu_timeline.py to shared_modules
pupil-labs/pupil pull request #2151
Opened 2021-06-21 17:08 UTC by N-M-T

@romanroibu My original method for determining whether or not a PI recording was loaded was to identify the presence of IMU data (line 269). Then I used bool 'is_invisible_rec' to disable interaction with the Plugin (e.g. line 288) when it wasn't. 

I think these checks can safely be removed if the plugin is only loaded with PI recordings. However, there have been a few cases where the IMU was missing due to hardware failure. In which case it might be worth leaving these conditions in?

2021-06-22 19:54 UTC, romanroibu commented
@N-M-T @papr I've updated the plugin to prevent it from being loaded by default unless:
- Player is running
- Recording was made using Pupil Invisible
- Recording contains IMU data

Also removed the checks that Neil mentioned above. Tested this behaviour with a Pupil Invisible recording and a Pupil Capture recording.

2021-06-22 19:54 UTC, romanroibu approved these changes

2021-06-23 13:25 UTC, papr requested changes

2021-06-23 13:25 UTC, papr commented on pupil_src/shared_modules/imu_timeline.py
> +    icon_font = "pupil_icons"
This currently corresponds to the `Vis Polyline` plugin icon. I suggest finding an alternative icon.

2021-07-07 08:38 UTC, papr approved these changes

2021-07-07 08:38 UTC, merged